[package]
name = "erc4906"
version = "0.2.0"
edition = "2024_07"
cairo-version = "2.8.4"
authors = ["Tekkac <tekkac@proton.me>"]

[lib]

[dependencies]
starknet = ">=2.8.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.18.0" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.26.0" }

[[target.starknet-contract]]
sierra = true
casm = false

[scripts]
test = "snforge test"
