[package]
name = "erc4906"
version = "0.3.0"
edition = "2024_07"
cairo-version = "2.8.4"
authors = ["Tekkac <tekkac@proton.me>"]

[lib]

[dependencies]
starknet = ">=2.8.4"
openzeppelin_access = "0.19.0"
openzeppelin_introspection = "0.19.0"
openzeppelin_token = "0.19.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.33.0" }

[[target.starknet-contract]]
sierra = true
casm = false

[scripts]
test = "snforge test"
