[package]
name = "erc4906"
version = "0.1.0"
edition = "2023_11"
cairo-version = "2.5.4"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[lib]

[dependencies]
starknet = ">=2.5.3"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.10.0" }

[scripts]
test = "snforge test"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.20.1" }

[[target.starknet-contract]]
sierra = true
casm = false

